package com.finfreedom.agent.integration;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.finfreedom.agent.config.IntegrationProperties;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.autoconfigure.condition.ConditionalOnBean;
import org.springframework.stereotype.Service;

/**
 * Confluence integration via Atlassian MCP server.
 * <p>
 * Stores pipeline artifacts as Confluence pages: design docs from the
 * Architect agent, test plans from QA, review reports from Reviewer.
 */
@Slf4j
@Service
@RequiredArgsConstructor
@ConditionalOnBean(McpToolService.class)
public class ConfluenceIntegrationService {

    private final McpToolService mcpToolService;
    private final IntegrationProperties properties;
    private final ObjectMapper objectMapper;

    /**
     * Create a Confluence page with pipeline output.
     *
     * @param title    page title
     * @param content  page content in Confluence storage format (XHTML) or markdown
     * @param parentId optional parent page ID for nesting under a project page
     * @return JSON result including page ID and URL
     */
    public String createPage(String title, String content, String parentId) {
        log.info("Creating Confluence page: '{}'", title);
        ObjectNode args = objectMapper.createObjectNode();
        // @xuandev/atlassian-mcp expects spaceId; we store the space key in config
        // and use it as-is since the tool resolves both key and ID
        args.put("spaceId", properties.getConfluence().getSpaceKey());
        args.put("title", title);
        args.put("body", content);
        if (parentId != null) {
            args.put("parentId", parentId);
        }
        return mcpToolService.invokeTool("confluence_create_page", args.toString());
    }

    /**
     * Update an existing Confluence page.
     */
    public String updatePage(String pageId, String title, String content, int version) {
        log.info("Updating Confluence page: {} ({})", pageId, title);
        ObjectNode args = objectMapper.createObjectNode();
        args.put("pageId", pageId);
        args.put("title", title);
        args.put("body", content);
        args.put("version", version);
        return mcpToolService.invokeTool("confluence_update_page", args.toString());
    }

    /**
     * Search Confluence pages using CQL.
     */
    public String searchPages(String cql) {
        ObjectNode args = objectMapper.createObjectNode();
        args.put("cql", cql);
        args.put("limit", 25);
        return mcpToolService.invokeTool("confluence_search", args.toString());
    }

    /**
     * Get a Confluence page by ID.
     */
    public String getPage(String pageId) {
        ObjectNode args = objectMapper.createObjectNode();
        args.put("pageId", pageId);
        return mcpToolService.invokeTool("confluence_get_page", args.toString());
    }

    /**
     * Store a design document from the Architect agent output.
     */
    public String storeDesignDoc(String issueKey, String designContent) {
        String title = "[" + issueKey + "] Technical Design — AI Generated";
        return createPage(title, formatAsStorageFormat(designContent), null);
    }

    /**
     * Store a test plan from the QA agent output.
     */
    public String storeTestPlan(String issueKey, String testPlanContent) {
        String title = "[" + issueKey + "] Test Plan — AI Generated";
        return createPage(title, formatAsStorageFormat(testPlanContent), null);
    }

    /**
     * Store a code review report from the Reviewer agent output.
     */
    public String storeReviewReport(String issueKey, String reviewContent) {
        String title = "[" + issueKey + "] Code Review Report — AI Generated";
        return createPage(title, formatAsStorageFormat(reviewContent), null);
    }

    /**
     * Wrap markdown-style content in basic Confluence storage format.
     * For a demo, we keep it simple with preformatted blocks.
     */
    private String formatAsStorageFormat(String markdownContent) {
        return """
                <ac:structured-macro ac:name="info">
                  <ac:rich-text-body>
                    <p>This page was auto-generated by the AI SDLC Pipeline.</p>
                  </ac:rich-text-body>
                </ac:structured-macro>
                <ac:structured-macro ac:name="code">
                  <ac:parameter ac:name="language">markdown</ac:parameter>
                  <ac:plain-text-body><![CDATA[%s]]></ac:plain-text-body>
                </ac:structured-macro>
                """.formatted(markdownContent);
    }
}
